[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "cython",
            "oldest-supported-numpy",
            "extension-helpers"]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "ndcombine/version.py"
