name: Run unit tests

on:
  pull_request:
  push:
    branches: [ main ]
    tags:
  workflow_dispatch:
  schedule:
    - cron: 45 4 * * 0

jobs:
  tests:
    name: ${{ matrix.name }} (${{ matrix.os }}, ${{ matrix.toxenv }})
    runs-on: ${{ matrix.os }}
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.8
            toxenv: py38
            coverage: true

          - os: macos-latest
            python-version: 3.9
            toxenv: py39

          - os: ubuntu-latest
            python-version: "3.10"
            toxenv: py310

          - name: Code style checks
            os: ubuntu-latest
            python-version: 3.9
            toxenv: codestyle

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install tox
    # - name: Install graphviz dependency
    #   if: "endsWith(matrix.toxenv, 'build_docs')"
    #   run: sudo apt-get -y install graphviz
    - name: Run tests
      if: "! matrix.coverage"
      run: tox -v -e ${{ matrix.toxenv }}
    - name: Run tests with coverage
      if: "matrix.coverage"
      run: |
        pip install Cython extension-helpers numpy
        COVERAGE=1 pip install -e .[test]
        pytest --pyargs ndcombine --cov ndcombine
    - name: Upload coverage to codecov
      if: "matrix.coverage"
      run: |
        pip install codecov
        codecov
